@startuml

package "es.mastercloud.mastermind"{}
package "java.util"{}
package "java.io"{}
package "es.mastercloud.utils"{}
package "es.mastercloud.mastermind.views.console"{}
package "es.mastercloud.mastermind.views"{}
package "es.mastercloud.mastermind.controllers"{}




@enduml