@startuml
title Class Diagram
class Mastermind
class Board
class Player
class MakerPlayer
class BreakerPlayer
class Combination
class SecretCombination
class ProposedCombination
class Goal
class Result
class WinnerResult
class Success
class Black
class White
class Position
class Color
class Red
class Blue
class Yellow
class Green
class Orange
class Purple

Combination <|-down- SecretCombination
Combination <|-down- ProposedCombination

Player <|-down- MakerPlayer
Player <|-down- BreakerPlayer

Goal <|-down- WinnerResult
Result <|-down- WinnerResult

Success <|-down- Black
Success <|-down- White

Color <|-down- Red
Color <|-down- Blue
Color <|-down- Yellow
Color <|-down- Green
Color <|-down- Orange
Color <|-down- Purple

Mastermind *-down-> Board
Mastermind *-down-> Turn
Mastermind *-down->"2" Player
Turn -down->"2" Player
Board *-down-> SecretCombination
Board o-down->"0..10" Result
Board o-down-> ProposedCombination
Result -down->"0..10" ProposedCombination
BreakerPlayer -down->"0..10" ProposedCombination
MakerPlayer -down-> SecretCombination
Result *-down->"0..4" Success
BreakerPlayer -down-> Goal
WinnerResult -down->"4" Black
Position -down-> Black
Combination *-down->"4" Position
Position o-down-> Color
Success --down-> Color

@enduml