@startuml

    package mastermind #DDDDDD { }
    package mastermind.models #DDDDDD { }
    package mastermind.controller #DDDDDD{ }
    package mastermind.views #DDDDDD { }
    package mastermind.utils #DDDDDD { }
    package java.util{ }
    package java.io{ }

    mastermind .down.> mastermind.controller
    mastermind .down.> mastermind.views
    mastermind.controller .down.> mastermind.models
    mastermind.views .down.> mastermind.controller
    mastermind.views .down.> mastermind.utils
    mastermind.models .down.> java.util
    mastermind.utils .down.> java.io

@enduml